//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommerce.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim bulunamadı!.
        /// </summary>
        public static string bildirimBulunamadi {
            get {
                return ResourceManager.GetString("bildirimBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim eklenirken hata oluştu!.
        /// </summary>
        public static string bildirimEklenirkenHata {
            get {
                return ResourceManager.GetString("bildirimEklenirkenHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim okundu olarak işaretlenemedi!.
        /// </summary>
        public static string bildirimOkunduYapilamadi {
            get {
                return ResourceManager.GetString("bildirimOkunduYapilamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim okundu olarak işaretlendi.
        /// </summary>
        public static string bildirimOkunduYapildi {
            get {
                return ResourceManager.GetString("bildirimOkunduYapildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler başarıyla gönderilmiştir..
        /// </summary>
        public static string bilgilerBasariylaGonderilmistir {
            get {
                return ResourceManager.GetString("bilgilerBasariylaGonderilmistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaza ait token başarıyla eklenmiştir!.
        /// </summary>
        public static string cihazTokenBasariylaKaydedildi {
            get {
                return ResourceManager.GetString("cihazTokenBasariylaKaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaza ait token eklenemedi!.
        /// </summary>
        public static string cihazTokenEklenemedi {
            get {
                return ResourceManager.GetString("cihazTokenEklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bildirim almak istemediğinden dolayı token kaydedilmedi!.
        /// </summary>
        public static string cihazTokenKaydedilmedi {
            get {
                return ResourceManager.GetString("cihazTokenKaydedilmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token daha önce zaten eklenmiştir!.
        /// </summary>
        public static string cihazTokenZatenKayitli {
            get {
                return ResourceManager.GetString("cihazTokenZatenKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen bulunamadı!.
        /// </summary>
        public static string gonderenBulunamadi {
            get {
                return ResourceManager.GetString("gonderenBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen bulunamadı!.
        /// </summary>
        public static string gonderilenBulunamadi {
            get {
                return ResourceManager.GetString("gonderilenBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla eklenmiştir..
        /// </summary>
        public static string kayitBasariylaEklendi {
            get {
                return ResourceManager.GetString("kayitBasariylaEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla güncellendi..
        /// </summary>
        public static string kayitBasariylaGuncellendi {
            get {
                return ResourceManager.GetString("kayitBasariylaGuncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla kaydedildi.
        /// </summary>
        public static string kayitBasariylaKaydedildi {
            get {
                return ResourceManager.GetString("kayitBasariylaKaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string kayitBasariylaSilindi {
            get {
                return ResourceManager.GetString("kayitBasariylaSilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        public static string kayitBulunamadi {
            get {
                return ResourceManager.GetString("kayitBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt eklenemedi!.
        /// </summary>
        public static string kayitEklenemedi {
            get {
                return ResourceManager.GetString("kayitEklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt güncellenemedi!.
        /// </summary>
        public static string kayitGuncellenemedi {
            get {
                return ResourceManager.GetString("kayitGuncellenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt reddedilmiştir.
        /// </summary>
        public static string kayitReddedilmistir {
            get {
                return ResourceManager.GetString("kayitReddedilmistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının adını belirtiniz!.
        /// </summary>
        public static string kullaniciAdiBelirtiniz {
            get {
                return ResourceManager.GetString("kullaniciAdiBelirtiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı!.
        /// </summary>
        public static string kullaniciBulunamadi {
            get {
                return ResourceManager.GetString("kullaniciBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri göndermediniz!.
        /// </summary>
        public static string veriGondermediniz {
            get {
                return ResourceManager.GetString("veriGondermediniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkisiz erişim!.
        /// </summary>
        public static string yetkisizErisim {
            get {
                return ResourceManager.GetString("yetkisizErisim", resourceCulture);
            }
        }
    }
}
